# This file defines the "module" itself.
# It tells GitHub what inputs it takes and how to run it.
name: 'MISS Framework - BLH Scanner'
description: 'Scans a repository for hijackable broken links based on the MISS framework.'
author: 'Gaurav Bhatia & Raj Sharma'

inputs:
  scan-directory:
    description: 'The directory to scan. Defaults to the root.'
    required: false
    default: '.'
  report-name:
    description: 'The name of the JSON report file.'
    required: false
    default: 'blh_report.json'
  # --- NEW ---
  # Add the level input to filter the noise
  level:
    description: "The minimum vulnerability level to report: 'warning' (all broken) or 'critical' (only hijackable)."
    required: false
    default: 'critical' 
  # --- END NEW ---

outputs:
  report-path:
    description: 'The path to the generated JSON report.'
    value: ${{ steps.run_scan.outputs.report_path }}

runs:
  using: 'composite' # This lets us run a series of simple shell commands
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run BLH Scanner
      id: run_scan
      shell: bash
      run: |
        python ${{ github.action_path }}/scan.py \
          --directory ${{ inputs.scan_directory }} \
          --output ${{ inputs.report-name }} \
          --level ${{ inputs.level }} # Pass the new level to the script
        
        echo "report_path=${{ inputs.report-name }}" >> $GITHUB_OUTPUT
